name: Check For Stale Repositories
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    name: Running test
    runs-on: windows-latest
    strategy:
      matrix:
       go: ['1.12']
    steps:
      - run: go run test_stale_repositories.go scripts.go
