name: tests

on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  build:
    name: Running test
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    - uses: actions/checkout@v3
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run tests
      run: go test -coverprofile=cover.out main_test.go main.go
    - name: Install Vim
      run: apt-get update; apt-get install -y vim;
    - name: Go Beautiful HTML Coverage
      uses: gha-common/go-beautiful-html-coverage@v1
